#ifndef IMGUI_CONFIG_BRENDER_H_
#define IMGUI_CONFIG_BRENDER_H_

#define IMGUI_IMPL_OPENGL_LOADER_CUSTOM
#include "gl.h"

#define IMGUI_DISABLE_OBSOLETE_FUNCTIONS
#endif /* IMGUI_CONFIG_BRENDER_H_ */
