#ifndef IMGUI_CONFIG_BRENDER_H_
#define IMGUI_CONFIG_BRENDER_H_

#define IMGUI_IMPL_OPENGL_LOADER_CUSTOM
#include <glad/glad.h>

#define IMGUI_DISABLE_OBSOLETE_FUNCTIONS
#endif /* IMGUI_CONFIG_BRENDER_H_ */
