/*
 * Copyright (c) 1993-1995 by Argonaut Technologies Limited. All rights reserved.
 *
 * $Id: order.h 1.1 1997/12/10 16:41:18 jon Exp $
 * $Locker: $
 *
 * Definitions for order tables and primitives
 */
#ifndef _ORDER_H_
#define _ORDER_H_

/*
 * Order table definitions
 */
enum {
    BR_ORDER_TABLE_LEAVE_BOUNDS = 0x0000,
    BR_ORDER_TABLE_NEW_BOUNDS   = 0x0001,
    BR_ORDER_TABLE_INIT_BOUNDS  = 0x0002,

    BR_ORDER_TABLE_CONVEX = 0x0004,

    BR_ORDER_TABLE_SORT_NEAR   = 0x0008,
    BR_ORDER_TABLE_SORT_FAR    = 0x0010,
    BR_ORDER_TABLE_SORT_CENTRE = 0x0020,

    /*
     * Primitives will be sorted within buckets
     * upon insertion.
     */
    BR_ORDER_TABLE_BUCKET_SORT = 0x0040,
};

/*
 * Sort types
 */
enum {
    BR_SORT_AVERAGE      = 0x0001,
    BR_SORT_MIN          = 0x0002,
    BR_SORT_MAX          = 0x0003,
    BR_SORT_FIRST_VERTEX = 0x0004
};

/*
 * Primitive types
 */
enum {
    BR_PRIMITIVE_POINT    = BRT_POINT,
    BR_PRIMITIVE_LINE     = BRT_LINE,
    BR_PRIMITIVE_TRIANGLE = BRT_TRIANGLE
};

/**
 * \brief The primitive is an item of rendering data produced in the second phase of rendering.
 *
 * It is typically a lit face of a model, transformed into screen co-ordinates. It contains
 * sufficient information (some private) to be depth sorted and rendered to the destination pixel
 * map. The application programmer will only be handling primitives as far as is necessary to
 * determine whether the primitive should appear and in what order it should be rendered. Primitives
 * are only generated by BRender.
 */
typedef struct br_primitive {

    /**
     * \brief Each bucket within an order table is a linked list of primitives.
     *
     * The primitive contains the links in the form of this pointer. When a primitive is inserted into a
     * bucket, it is inserted at the head (the first bucket in the list). Upon rendering the buckets are
     * rendered from the head onwards. This member should not be modified.
     */
    struct br_primitive *next;

    /*
     * Cached calculated depth of the primitive.
     * Some devices may use this for sorting within the bucket.
     */
    br_scalar depth;

    /**
     * \brief There are currently three types of primitive: point, line and triangle.
     *
     * This member indicates the type of this primitive. It should not be modified. The following table
     * lists the symbols defining the value of each type.
     *
     * \li BR_PRIMITIVE_POINT — The primitive is a point defined by a single vertex
     * \li BR_PRIMITIVE_LINE — The primitive is a line defined by two vertices
     * \li BR_PRIMITIVE_TRIANGLE — The primitive is a triangle defined by three vertices
     */
    br_uint_32 type;

    /*
     * Properties
     */
    void *stored;

    /*
     * Pointers to vertex data
     */
    void *v[3];

} br_primitive;

/**
 * \brief This is an order table used by the Z-Sort renderer.
 *
 * It contains a table of pointers to linked lists of rendering primitives. The Z depth range of the
 * order table is divided into a number of equal intervals (buckets). Each primitive generated by
 * the Z-Sort renderer is inserted into the appropriate list so that it is eventually rendered in
 * order of depth. It is the application developer's task to determine a scheme so that the scene is
 * crudely segmented into layers of background through to foreground (with an order table for each
 * layer), and any mutually depth critical faces are sorted in order. It does not matter in which
 * order non-overlapping faces are drawn with respect to each other, so the trick is to sort only
 * overlapping faces that need sorting, i.e. concave models, or interpenetrating models.
 *
 * There is a facility of nominating a primary order table such that all other secondary order
 * tables are rendered in between its buckets. This provides a quick and easy way of progressing to
 * the next step, after having a single order table, i.e. a primary order table for static features
 * and individual order tables for models.
 *
 * Order tables are assigned to actors, either by default, inheritance or explicitly (see
 * BrZsActorOrderTableSet()).
 */
typedef struct br_order_table {

    /**
     * \brief A pointer to a list of heads of linked lists of primitives.
     *
     * Each linked list is effectively each bucket of the bucket sort (per order table). This member is
     * for internal use only. Each pointer will be NULL if the bucket is empty. Note that primitives are
     * allocated from the primitive heap supplied at the start of rendering
     */
    br_primitive **table;

    /**
     * \brief This member defines the number of intervals (buckets) that the z range is divided into.
     *
     * It also defines the number of pointers pointed to by table. An order table used for a single
     * opaque convex model need only have one bucket, whereas a complex model actor with several child
     * models (within the z range of the parent) might need several intervals.
     */
    br_uint_16 size;

    /**
     * \brief Pointer to the next order table (next lowest min_z).
     *
     * NULL at end of list. Each rendering, this list is constructed (before drawing), and then
     * deconstructed (after drawing). This member should only be non-NULL during rendering, i.e. within
     * a rendering call-back function such as br_model_custom_cbfn. This member is for internal use
     * only.
     */
    struct br_order_table *next;

    /**
     * \brief Range of z depths over which to sort.
     *
     * Any z depths of vertices outside this range will be clamped to the limits. Note that the z depth
     * values are a result of a linear mapping from camera co-ordinate space, of the range [-hither_z,
     * -yon_z] to the range [-hither_z, +yon_z]. These members are usually set by using the
     * BR_ORDER_TABLE_NEW_BOUNDS or BR_ORDER_TABLE_INIT_BOUNDS flags, but can be set explicitly using
     * the BrZsScreenZToDepth() functions. Note that BrOriginToScreenXYZO(), BrPointToScreenXYZO() and
     * BrPointToScreenXYZOMany() return projected screen z ordinates, not depths. The z range
     * \f$(max\_z - min\_z)\f$ must be greater than 0.001, otherwise it will be forced to this range.
     */
    br_scalar min_z;
    /**
     * \brief Range of z depths over which to sort.
     *
     * Any z depths of vertices outside this range will be clamped to the limits. Note that the z depth
     * values are a result of a linear mapping from camera co-ordinate space, of the range [-hither_z,
     * -yon_z] to the range [-hither_z, +yon_z]. These members are usually set by using the
     * BR_ORDER_TABLE_NEW_BOUNDS or BR_ORDER_TABLE_INIT_BOUNDS flags, but can be set explicitly using
     * the BrZsScreenZToDepth() functions. Note that BrOriginToScreenXYZO(), BrPointToScreenXYZO() and
     * BrPointToScreenXYZOMany() return projected screen z ordinates, not depths. The z range
     * \f$(max\_z - min\_z)\f$ must be greater than 0.001, otherwise it will be forced to this range.
     */
    br_scalar max_z;

    /**
     * \brief This member defines the value of z used to determine the position at which this order
     *        table is in the list of order tables.
     *
     * This value is typically set to min_z, and may be set explicitly or automatically at the same time
     * as min_z and max_z. There are flags available which can be used to specify how sort_z is
     * calculated. Note that this member is not relevant to primary order tables.
     */
    br_scalar sort_z;

    /*
     * Scale for sorted depths
     */
    br_scalar scale;

    /**
     * \brief At some point the z range of each order table must be set appropriately.
     *
     * The z range is not only used to determine into which buckets each primitive should be placed, but
     * also in which order the order tables should be rendered. If the application knows in advance what
     * this range can be then the z range can be set before rendering begins (see BrZsScreenZToDepth()),
     * otherwise various flags can be used to get the z range to be calculated automatically. Note that
     * an order table is used in descendant order, that is, actors nearer the root of the hierarchy will
     * see the order table first. Once the hierarchy has been traversed, the order tables will be sorted
     * according to the value of sort_z, which can be set according to the values of min_z and max_z.
     * The order tables will be rendered furthest first (see also BrZsOrderTablePrimaryEnable()). The
     * flags are described in the following table.
     *
     * \li BR_ORDER_TABLE_LEAVE_BOUNDS — Z range is left unchanged (presumably preset)
     * \li BR_ORDER_TABLE_NEW_BOUNDS — Z range is recalculated from the bounds of each actor that uses
     *     it, just before each use. Note that the order table is sorted according to the last value of
     *     sort_z.
     * \li BR_ORDER_TABLE_INIT_BOUNDS — Z range is calculated from the bounds of the first actor that
     *     uses it (e.g. a BR_ACTOR_BOUNDS_CORRECT actor).
     * \li BR_ORDER_TABLE_CONVEX — Z range is ignored for bucket determination (primitives placed in
     *     first bucket, and not sorted), but other flags still apply for ordering the order table.
     * \li BR_ORDER_TABLE_SORT_NEAR — sort_z is set to min_z when the bounds are calculated
     * \li BR_ORDER_TABLE_SORT_CENTRE — sort_z is set to \f$(min\_z + max\_z) / 2\f$ when the bounds are calculated
     * \li BR_ORDER_TABLE_SORT_FAR — sort_z is set to max_z when the bounds are calculated
     *
     * The first three flags are mutually exclusive, as are the last three. Any one of the first three
     * may be combined with the fourth, and any one of the last three. Bounds can be computed from the
     * following actors: BR_ACTOR_MODEL, BR_ACTOR_BOUNDS and BR_ACTOR_BOUNDS_CORRECT. Note that when an
     * order table's bounds are calculated, they are always calculated from the full bounds of the model
     * (or bounds data structure). Therefore, it is possible, where bounds intersect the boundaries of
     * the viewing volume, for one of the order table bounds to lie outside the view space. All buckets
     * are still rendered, but the buckets outside the view space will be empty (unless a custom
     * primitive call-back has utilised them).
     */
    br_uint_32 flags;

    /**
     * \brief How primitives are inserted into an order table, obviously depends upon their depth, but
     *        for primitives with more than one z value, such as lines, triangles and quads, how to
     *        arrive at a single z value is not a clear cut decision.
     *
     * Because it depends so much upon the scene and the application, it is left to the application to
     * specify the way the sorting z should be obtained. The following table describes each type which
     * can be specified in this member.
     *
     * \li BR_SORT_FIRST_VERTEX — Arbitrary – the first vertex is as good as any
     * \li BR_SORT_MIN — The nearest vertex
     * \li BR_SORT_MAX — The furthest vertex
     * \li BR_SORT_AVERAGE — The average depth of vertices
     */
    br_uint_16 type;

    /**
     * \brief This member is used to determine when to clear and initialise the order table's z range
     *        (if required).
     *
     * This member is set to zero upon allocation and after rendering, and incremented each time it is
     * referenced by an actor traversed during rendering. When zero, the order table is cleared (and if
     * BR_ORDER_TABLE_INIT_BOUNDS is set, its z range calculated) when it is next referenced by an actor
     * traversed during rendering. This member is for internal use only.
     */
    br_uint_16 visits;

} br_order_table;

/*
 * workspace for storing primitives
 */
typedef struct br_primitive_heap {
    br_uint_8 *base;
    br_size_t  size;
    br_uint_8 *current;
} br_primitive_heap;

/*
 * structure used by ZsOrderTableTraversal
 */
typedef struct {
    br_scalar screenX;
    br_scalar screenY;
    br_scalar distanceZ;
} ot_vertex;

#endif
